name: relieve_app
description: Relieve Mobile App

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.2.1+1002001

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter  
  url_launcher: ^5.0.3
  flutter_page_indicator: ^0.0.3
  http: ^0.12.0+2
  validators: ^2.0.0+1
  email_validator: ^1.0.0
  flutter_cupertino_date_picker: ^1.0.0+1
  flutter_keychain: ^1.0.0
  recase: ^2.0.1
  flutter_stetho: ^0.2.2
  flutter_spinkit: ^3.1.0
  cached_network_image: ^0.8.0
  flushbar: ^1.6.0
  firebase_messaging: ^5.0.2
  google_maps_flutter: ^0.5.15+1
  permission_handler: ^3.1.0
  geolocator: ^5.0.0
  google_sign_in: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  image_test_utils: ^1.0.0


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: CircularStdBook
      fonts:
        - asset: fonts/circular-std-book.otf        
    - family: CircularStdMedium
      fonts:
        - asset: fonts/circular-std-medium.otf
    - family: CircularStdBold
      fonts:
        - asset: fonts/circular-std-bold.otf
    - family: CircularStdBlack
      fonts:
        - asset: fonts/circular-std-black.otf
    
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
